### ISSUE TITLE
Support other Python packaging formats

### ISSUE THREAD

**Issue by woodruffw** [pypa/pip-audit#73]
Outside of `requirements.txt`, there are a few other common Python packaging files:

- [x] A few different tools store requirements in `pyproject.toml` (#83)
- [ ] `poetry` puts locked (i.e., frozen) dependencies in `poetry.lock` (#84)
- [ ] `pipenv` uses `Pipfile` and `Pipfile.lock` (#85)

Each of these functionally boils down to a `RequirementsSource`, but with a bit of pre-processing to get them out of their dedicated formats.

**Comment by woodruffw** [comment]
Closing in favor of subissues, since we don't really need a roadmap-type tracker here.
